### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by TurtleP** [mtheall/tex3ds#10]
After compiling, it goes to configure and fails:

```
./configure: line 4414: PKG_PROG_PKG_CONFIG: command not found
./configure: line 4417: syntax error near unexpected token `ImageMagick,'
./configure: line 4417: `PKG_CHECK_MODULES(ImageMagick, Magick++ >= 6.0.0, , , )'
Makefile:40: recipe for target 'tex3ds' failed
make: *** [tex3ds] Error 2
```

Could I be missing something here?

**Comment by mtheall** [comment]
Resolved:
- building on WSL with non-package automake; change ACLOCAL_PATH
- ImageMagick outdated on WSL so minor patch applied for const-ness
- Remove --static from pkg-config in configure.ac
